language: r
r: 
 - 4.0.0

dist: xenial

services:
  - xvfb
  - postgresql

cache:
  packages: true
  directories:
    - _bookdown_files
    - $HOME/.npm
    
latex: false
pandoc_version: 2.7.3

env:
  global:
    - TZ="Asia/Shanghai"
    - MAKEFLAGS="-j 2"
    - RETICULATE_PYTHON_ENV="$HOME/.virtualenvs/r-tensorflow"

repos:
  CRAN: https://cloud.r-project.org
  Geo: https://nowosad.github.io/drat/

addons:
  apt:
    packages:
      ## install nloptr
      -  libnlopt-dev
      ## install rjags runjags
      -  jags  
      ## install Cairo plotly
      -  libcairo2-dev
      ## install xml2 igraph
      -  libxml2-dev
      -  libgmp-dev
      -  libglpk-dev
      ## install openssl
      -  libssl-dev
      ## install curl
      -  libcurl4-openssl-dev
      ## install git2r
      -  libgit2-dev
      ## install v8
      -  libnode-dev
      ## install DBI odbc 
      -  unixodbc
      -  unixodbc-dev
      -  odbc-postgresql
      -  libsqliteodbc
      ## install webshot
      -  phantomjs
      -  optipng
      -  imagemagick
      -  ghostscript
      -  graphviz
      -  cargo
      -  ffmpeg
      ## install magick
      -  libmagick++-dev
      # pdftools
      - libpoppler-cpp-dev
      ## install sf
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      ## rgl
      - libglu1-mesa-dev 
      - libx11-dev
      - virtualenv
      - python3-pip
      - python3-virtualenv
      - python3-tk

install:
  ## Python Env
  - virtualenv -p /usr/bin/python3 $RETICULATE_PYTHON_ENV
  - source $RETICULATE_PYTHON_ENV/bin/activate
  - python3 -V
  # Install modules
  - pip install -r requirements.txt
  - pip list --format=columns
  - deactivate

before_script:
  - mkdir -p ~/.R ~/.fonts
  - Rscript -e 'install.packages("tinytex"); tinytex:::install_prebuilt(); tinytex::tinytex_root()'
  - export PATH=$HOME/bin:$PATH
  - tlmgr update --self --all
  - tlmgr install ctex xecjk mdwtools zhnumber ulem ms xcolor unicode-math filehook lm-math
      subfig sourcecodepro sourceserifpro sourcesanspro cancel titlepic pgf preview psnfss
      jknapltx titlesec tocbibind tocloft trimspaces savesym environ fancyhdr listings
      psnfss realscripts relsize rsfs setspace soul xltxtra mathdesign epstopdf-pkg times
  - curl -fLo Adobe-Fonts.zip https://github.com/XiangyunHuang/fonts/releases/download/v0.1/Adobe-Fonts.zip
  - unzip Adobe-Fonts.zip -d ~/.fonts/adobe
  - fc-cache -fsv
  - Rscript -e "sessionInfo(.packages(T));capabilities()"
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE, checkBuilt = TRUE)'
  - Rscript -e "install.packages('remotes');remotes::install_deps()"
  - Rscript -e "install.packages('spDataLarge', repos = 'https://nowosad.github.io/drat')"
  - Rscript -e 'library(tikzDevice);tikzTest();tikzTest("$\\sin(x^2/2 - y^2/4 + 3) \\cos(2 x + 1 - \\exp(y))$")'


script:
  - export COMMIT_MSG=$(git log -1 --format='%h %<(50,trunc)%s')
  - export DEPLOY_MSG=${COMMIT_MSG//[\'\"\`]/}
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
  # build book
  - mkdir -p _book/interactives && cp -r interactives/* _book/interactives
#  - travis_wait 30 make gitbook

#script:
#  - export DOCKER_HOST_IP=$(ip route|awk '/docker0/ { print $9 }')
#  - mkdir -p _book/interactives && cp -r interactives/* _book/interactives
#  - docker-compose up -d
#  - docker-compose run book bash -c "cp odbc.ini ~/.odbc.ini;make gitbook"
#  - docker-compose down

after_success:
  - ./_deploy.sh

before_cache:
- nvm install stable
- npm install netlify-cli -g

deploy:
  - provider: script
    script: netlify deploy --dir _book --prod --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: netlify deploy --dir _book --message "$DEPLOY_MSG"    
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != "master"
