language: r
dist: xenial
services:
  - docker
cache:
  packages: true
  directories:
    - _bookdown_files
    - $HOME/.npm
    
latex: false
pandoc: false

env:
  global:
    - MAKEFLAGS="-j 2"
    - R_VERSION=3.6.1

before_script:
  - export COMMIT_MSG=$(git log -1 --format='%h %<(50,trunc)%s')
  - export DEPLOY_MSG=${COMMIT_MSG//[\'\"\`]/}
  - export DOCKER_HOST_IP=$(ip route|awk '/docker0/ { print $9 }')
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - mkdir -p _book/interactives && cp -r interactives/* _book/interactives
  #- docker-compose up -d
  - docker-compose run book bash -c "cp odbc.ini ~/.odbc.ini;make all"
  - docker-compose down
  - ./_deploy.sh

after_success:
- nvm install stable
- npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy --prod --dir _book --message "$DEPLOY_MSG"
  skip_cleanup: true
