# 数据可视化 {#chap:data-visualization}

图层，几何，统计，坐标，刻度，分组，切片，图例，注释，字体，配色，主题

> 3-D bar plots are an abomination. Just because Excel can do them doesn't mean you should. (Dismount pulpit).
>
>   --- Berton Gunter [^BG-help-2007]
      

[^BG-help-2007]: <https://stat.ethz.ch/pipermail/r-help/2007-October/142420.html>
<!-- 更重要的是作图的原则，精准，美观 -->

```{r}
library(ggplot2)
```

grid graphics lattice 和 ggplot2 之间的历史发展关系脉络

gganimate 只是一个扩展，并不是新的东西，因为它是静态图形转化为帧，然后借助第三方工具合成

ggplot2 生态系统 \@ref(tab:ggplot2-eco)

```{r ggplot2-eco,echo=FALSE}
library(magrittr)
pdb <- tools::CRAN_package_db()
subset(pdb, subset = grepl("^gg", pdb$Package), select = c("Package", "Title")) %>%
  transform(., Title = gsub("(\\\n)", " ", Title), Package = paste("**", Package, "**", sep = "")) %>%
  transform(., Title = gsub("'(ggplot2|RJDemetra|ggplot|ggiraph|partykit|RStudio|UpSet|ggmap|stats|Geoms|table1|Plotly|grob)'", "\\1", Title)) %>%
  knitr::kable(.,
    caption = "ggplot2 生态系统", format = "pandoc",
    booktabs = TRUE, row.names = FALSE
  )
```

## 坐标轴 {#subsec:axis}

标签，刻度，旋转，字体，颜色，极坐标，不同的坐标系

## 图例


## 主题

### 配色

### 字体

